import csstyle
from flask import (
    Flask, Response, render_template, request, send_from_directory, redirect,
    url_for)

    @app.route('/css/csstyle.css')
    def stylesheet():
        """CSS stylesheet created by CSStyle."""
        local_filename = os.path.join('static', 'css', 'style.css')
        filenames = (
            os.path.join(SITE_ROOT, local_filename),
            os.path.join(project_root, local_filename))

        text = '/* Generated by CSStyle */\n\n'

        for filename in filenames:
            text += open(filename).read()

        for engine in csstyle.BROWSERS:
            browser_parser = getattr(csstyle, engine)
            parser = csstyle.Parser(filenames)
            text += '\n\n/* CSS for %s */\n\n' % engine
            text += repr(browser_parser.transform(parser, keep_existant=False))
        return Response(text, mimetype='text/css')


    @app.route('/<folder>/<path:path>')
    def static_file(folder, path):
        """Static files."""
        filename = os.path.join('static', folder, path)
        for base in (project_root, SITE_ROOT):
            if os.path.isfile(os.path.join(base, filename)):
                return send_from_directory(base, filename)
        raise NotFound

